#workflows
#jobs
#steps
#actions

name: CICD

on:
  workflow_dispatch: 

jobs:
    code:
      runs-on: ubuntu-latest
      steps:
        - name: code
          run: echo "code"
      
    build:
      needs: [code]
      runs-on: ubuntu-latest
      steps:
        - name: build
          run: echo "build"
          
    test:
      needs: [build]
      runs-on: ubuntu-latest
      steps:
        - name: test
          run: echo "test"

    deploy:
     needs: [build,test]
     runs-on: ubuntu-latest
     steps:
        - name: deploy
          run: echo "deploy"     
          
   
